### ISSUE TITLE
Result sounds like bot not real person.

### ISSUE THREAD

**Issue by PriyamJha0124** [JarodMica/StyleTTS-WebUI#33]
I successfully trained the STT2 model and synthesized a cloned audio result. 

However, the output sounds more like a bot than a real person.

Will using longer training data solve this problem? Or do I need to handle any parameters?

Thank you.

**Comment by JarodMica** [comment]
2 minutes may not be enough audio, I recommend at least 20 to get good results. Training longer will probably make it worse as the model will diverge away from the large pretraining that was done, it's best to try and add more audio.

**Comment by JarodMica** [comment]
> Thank you for your answer.
> 
> Is there any recommendation about setting the epochs for 20minutes of audio?

Default values are what I use. Recommend you go through this: https://github.com/yl4579/StyleTTS2/discussions/81

You'll also find more info about joint and diffusion training there.

You probably got NaN value in for sigma inside of your config file, but without the error you're running into, it's hard to actually diagnose what your issue is.

Issue at hand resolved, please open a new issue if you want to continue with errors
