### ISSUE TITLE
[Question] Is this project open for contrubition?

### ISSUE THREAD

**Issue by emrahtoy** [JarodMica/StyleTTS-WebUI#5]
Hello @JarodMica , i just wanted to ask if this project is open for contributions.
You haven't commented on any of the issues opened in the past so I wanted to ask because I did not mean any disrespectful behave.

**Comment by JarodMica** [comment]
Contributions are welcome, but if you want to modify it for your convenience, I recommend working and branching off instead of trying to merge back into mine.

I'm quite a stickler for adding new code into my projects, meaning I usually want to bug test things to make sure it works properly and the catch with that is it adds more things on my plate to do.  The biggest reason I haven't responded too much is I'm just busy. I'll get to it eventually to fix things up, but that'll be after this webui is stable.

**Comment by emrahtoy** [comment]
Quite understandable, we all have the same concerns. I thank you for the reply and the project @JarodMica

**Comment by SAT431** [comment]
Building wheels for collected packages: monotonic_align
Building wheel for monotonic_align (pyproject.toml) ... error
error: subprocess-exited-with-error

× Building wheel for monotonic_align (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [1 lines of output]
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for monotonic_align
Failed to build monotonic_align
ERROR: Could not build wheels for monotonic_align, which is required to install pyproject.toml-based projects

NOTE: i have vs c++ installed and working properly and even though Iam facing this issue
